# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Shots by Satyam"
subtitle: "A chapter from my life"
author:  "Satyam Patil"
header:
 title: "Shots"
 subtitle: "by Satyam Patil"
footer:
 name: "Heyy!'"
 bio: "I'm Satyam Patil — a passionate photographer with a love for capturing the raw emotion, vivid landscapes, and dynamic life of the streets. Whether it's the subtle play of light on someone's face or the hustle of a city corner, I aim to freeze moments that tell real stories."

social_urls:
  instagram: "https://www.instagram.com/satyamawk/"

